### ISSUE TITLE
PlayerInput Class

### ISSUE THREAD

**Issue by stott531** [NoahRoseLedesma/thick-turtle#3]
If we are using the sfml event library, creating a player input class may be redundant. The library already has a type `sf::Event` that we can use in place of the current player input class placeholder. I can create a wrapper if you want though.

**Comment by NoahRoseLedesma** [comment]
The more I think about it the more I think we should rethink the player input class. Player input should be purely for human players to bundle these two pieces of data together, which tile the user interacted with, and what was the interaction (left mouse, right mouse, keypress, etc..)

The AI player will 'think' not by passing input but by using the methods we have defined for all players such as Piece::Move and Piece::Attack

**Comment by stott531** [comment]
Well, it wouldn't be hard to override the class for AI Player input. Until we get a few other things working, I don't believe we'll be able to get the tile that the player clicked on

**Comment by NoahRoseLedesma** [comment]
I think that PlayerInput as a datatype is an unnecessary abstraction. I think this is a case where taking a more functional approach will be better suited.

I see human players having a function which polls SFML for mouse events and then immediately decoding that mouse event into an action (highlighting a tile, ordering a unit to attack, etc.)
