### ISSUE TITLE
Accessing the Map

### ISSUE THREAD

**Issue by stott531** [NoahRoseLedesma/thick-turtle#4]
So in trying to write some actual code for the pieces class, there are a couple of times when I need to access other tiles on the map to determine if they are valid. Furthermore, there may be unforeseen things in the future which may require access to the map. The two solutions I've come up with both have some big drawbacks. Let me know which you think is better or if there is another better option that I'm not thinking of. If I had to choose, option 1 is probably the safer way to go.
### Option 1: Make a pointer to the map a member variable of each piece 
This seems quite inefficient since it will essentially increase the memory size of each piece in order to access the exact same information. Not to mention, this adds another responsibility to the constructor.
### Option 2: Implement Map as a pure singleton
This would mean making a static instance of the class than can be called from anywhere in the program using a static getter method. The drawbacks on this are pretty big since the object will essentially have the lifetime of the entire program, and it will make unit testing nearly impossible in the future since methods will essentially be dependent upon each other, which, as you know, is big no no for unit testing. Also, this option is not completely thread safe, which may be a problem if we ever have to thread anything.

**Comment by NoahRoseLedesma** [comment]
In the tile class I was storing a pointer to the map in each element. The thought process was that we could end up having multiple maps in a single game. Storing the pointer to the map is a relatively small overhead if you're thinking in orders of magnitude.

A single texture loaded in memory for a 100x100 tile is going to take the space of 10,000 map pointers.

I think we should avoid the singleton design for the map and store the pointers.
